<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CivicConnect.Core\CivicConnect.Core.csproj" />
    <ProjectReference Include="..\CivicConnect.Data\CivicConnect.Data.csproj" />
  </ItemGroup>

</Project>
